cache:
- apt
language: python
python:
- 2.7
- 3.4
- 3.5
env:
- INSTALL_DEB_DEPENDECIES=true NIPYPE_EXTRAS="doc,tests,fmri,profiler"
- INSTALL_DEB_DEPENDECIES=false NIPYPE_EXTRAS="doc,tests,fmri,profiler"
- INSTALL_DEB_DEPENDECIES=true NIPYPE_EXTRAS="doc,tests,fmri,profiler,duecredit"
before_install:
- function bef_inst {
  if $INSTALL_DEB_DEPENDECIES; then sudo rm -rf /dev/shm; fi &&
  if $INSTALL_DEB_DEPENDECIES; then sudo ln -s /run/shm /dev/shm; fi &&
  bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh) &&
  sudo apt-get -y update &&
  sudo apt-get -y install xvfb fusefat graphviz &&
  if $INSTALL_DEB_DEPENDECIES; then travis_retry sudo apt-get install -y -qq
  fsl afni elastix fsl-atlases; fi &&
  if $INSTALL_DEB_DEPENDECIES; then
    source /etc/fsl/fsl.sh;
    source /etc/afni/afni.sh;
    export FSLOUTPUTTYPE=NIFTI_GZ; fi &&
  wget https://repo.continuum.io/archive/Anaconda${TRAVIS_PYTHON_VERSION:0:1}-4.3.0-Linux-x86_64.sh
  -O /home/travis/.cache/anaconda.sh &&
  bash /home/travis/.cache/anaconda.sh -b -p /home/travis/anaconda &&
  export PATH=/home/travis/anaconda/bin:$PATH &&
  conda config --add channels conda-forge &&
  conda update --all -y python=$TRAVIS_PYTHON_VERSION &&
  conda install -y numpy scipy;
  }
- travis_retry bef_inst
install:
#  Add install of vtk and mayavi to test mesh (disabled): conda install -y vtk mayavi &&
- travis_retry pip install -e .[$NIPYPE_EXTRAS]
script:
- py.test --doctest-modules nipype
deploy:
  provider: pypi
  user: satra
  password:
    secure: OCO0FXb4f+pH4Uw7zWCIRp3qOJ1t7rhky4K8MjNU8tyVCJgd6O/Bv8GJgceS0LktPodlAAjB8SxAhTORPAQZ1D/44PJYy3NQIisvej1zjLpaA9TEGfl6W7MqhDpRyMHW+cnSi/n84SAmdr+Z4vOxScDHdwr13EPmGyOIlHMAGnE=
  on:
    tags: true
    repo: nipy/nipype
    branch: master
  distributions: "sdist"
