language: python
python:
    - "2.7"
before_install:
    - deactivate
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-scipy python-nose
    - sudo apt-get install -qq python-networkx python-traits python-setuptools
    - virtualenv --system-site-packages ~/virtualenv/this
    - source ~/virtualenv/this/bin/activate
    - easy_install$PYSUF nibabel # Latest pypi
install: python setup.py build_ext --inplace
script: make test