cache:
- apt
language: python
python:
- 2.7
- 3.4
- 3.5
env:
- INSTALL_DEB_DEPENDECIES=true
- INSTALL_DEB_DEPENDECIES=false
before_install:
- if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then export PATH=/home/travis/miniconda2/bin:$PATH; else export PATH=/home/travis/miniconda3/bin:$PATH; fi
- if $INSTALL_DEB_DEPENDECIES; then sudo rm -rf /dev/shm; fi
- if $INSTALL_DEB_DEPENDECIES; then sudo ln -s /run/shm /dev/shm; fi
- bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
- sudo apt-get -y update
- sudo apt-get -y install xvfb
- if $INSTALL_DEB_DEPENDECIES; then travis_retry sudo apt-get install -y -qq --no-install-recommends
  fsl afni elastix; fi
- if $INSTALL_DEB_DEPENDECIES; then travis_retry sudo apt-get install -y -qq fsl-atlases;
  fi
- if $INSTALL_DEB_DEPENDECIES; then source /etc/fsl/fsl.sh; fi
- if $INSTALL_DEB_DEPENDECIES; then source /etc/afni/afni.sh; fi
- export FSLOUTPUTTYPE=NIFTI_GZ
install:
- sudo apt-get install fusefat
- conda update --yes conda
- conda config --add channels conda-forge
- conda create -n testenv --yes pip numpy scipy nose networkx python-dateutil nipype python=$TRAVIS_PYTHON_VERSION
- source activate testenv
- if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then conda install --yes vtk; fi
- if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then pip install ordereddict; fi
# Doctests
- pip install python-coveralls nose-cov
- export DOCTEST_UNICODE=""
- if [ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]; then export DOCTEST_UNICODE="--with-doctest-ignore-unicode"; pip install doctest-ignore-unicode; fi
- pip install -r requirements.txt
- pip install -e .
script:
- python -W once:FSL:UserWarning:nipype `which nosetests` --with-doctest ${DOCTEST_UNICODE} --with-cov --cover-package nipype --cov-config .coveragerc --logging-level=DEBUG --verbosity=3
after_success:
- coveralls --config_file .coveragerc
deploy:
  provider: pypi
  user: satra
  password:
    secure: OCO0FXb4f+pH4Uw7zWCIRp3qOJ1t7rhky4K8MjNU8tyVCJgd6O/Bv8GJgceS0LktPodlAAjB8SxAhTORPAQZ1D/44PJYy3NQIisvej1zjLpaA9TEGfl6W7MqhDpRyMHW+cnSi/n84SAmdr+Z4vOxScDHdwr13EPmGyOIlHMAGnE=
  on:
    tags: true
    repo: nipy/nipype
    branch: master
  distributions: "sdist"
