cache:
- apt
language: python
python:
- 2.7
- 3.4
- 3.5
env:
- INSTALL_DEB_DEPENDECIES=true
- INSTALL_DEB_DEPENDECIES=false
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh
  -O /home/travis/.cache/miniconda.sh
- bash /home/travis/.cache/miniconda.sh -b -p /home/travis/miniconda
- export PATH=/home/travis/miniconda/bin:$PATH
- if $INSTALL_DEB_DEPENDECIES; then sudo rm -rf /dev/shm; fi
- if $INSTALL_DEB_DEPENDECIES; then sudo ln -s /run/shm /dev/shm; fi
- bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
- sudo apt-get -y update
- sudo apt-get -y install xvfb fusefat
- if $INSTALL_DEB_DEPENDECIES; then travis_retry sudo apt-get install -y -qq --no-install-recommends
  fsl afni elastix; fi
- if $INSTALL_DEB_DEPENDECIES; then travis_retry sudo apt-get install -y -qq fsl-atlases; fi
- if $INSTALL_DEB_DEPENDECIES; then
  source /etc/fsl/fsl.sh; fi
  source /etc/afni/afni.sh; fi
- export FSLOUTPUTTYPE=NIFTI_GZ
install:
- conda config --add channels conda-forge
- conda update --yes conda
- conda update --all -y python=$TRAVIS_PYTHON_VERSION
- conda install vtk mayavi
- conda install nipype
- pip install python-coveralls nose-cov doctest-ignore-unicode
- rm -r /home/travis/miniconda/lib/python${TRAVIS_PYTHON_VERSION}/site-packages/nipype*
- pip install -r requirements.txt
- pip install -e .
script:
- python -W once:FSL:UserWarning:nipype `which nosetests` --with-doctest --with-doctest-ignore-unicode --with-cov --cover-package nipype --cov-config .coveragerc --logging-level=DEBUG --verbosity=3
after_success:
- coveralls --config_file .coveragerc
deploy:
  provider: pypi
  user: satra
  password:
    secure: OCO0FXb4f+pH4Uw7zWCIRp3qOJ1t7rhky4K8MjNU8tyVCJgd6O/Bv8GJgceS0LktPodlAAjB8SxAhTORPAQZ1D/44PJYy3NQIisvej1zjLpaA9TEGfl6W7MqhDpRyMHW+cnSi/n84SAmdr+Z4vOxScDHdwr13EPmGyOIlHMAGnE=
  on:
    tags: true
    repo: nipy/nipype
    branch: master
  distributions: "sdist"
